version: '3'

services:
#  my_app:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    command: ./my_app_start
#    environment:
#      - pass=${pass}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${pass}
      MYSQL_DATABASE: golang
    ports:
      - '3306:3306'
    volumes:
#      - mysql-data:/var/lib/mysql
      - './_sql/:/docker-entrypoint-initdb.d/'

  redis:
    image: 'redis'
    ports:
      - '6379:6379'
#
#volumes:
#  mysql-data:
#    driver: local
